Cleanup
skaut/Skautis pull request #85
Opened 2019-10-06 18:01 UTC by JindrichPilar

Drobne zmeny, doporucuji cist po commetch. Nechtel jsem otravovat spoustou malych pullrequestu.

2019-11-29 14:34 UTC, fmasa requested changes
Obecně LGTM, našel jsem jen pár drobností

2019-11-29 14:34 UTC, fmasa commented on src/User.php
>          } catch (\Exception $e) {
Nebylo by tady lepší vyhazovat tu výjimku? Co tady reálně může nastat?

2019-11-29 14:34 UTC, fmasa commented on src/User.php
> -        return $this->setLoginData();
Teď by mělo být reálné aspoň část těch parametrů v `setLoginData()` udělat povinných - protože volání `$user->setLoginData()` nedává smysl

2019-11-29 14:34 UTC, fmasa commented on src/Helpers.php
>          throw new StaticClassException;
Tuhle výjimku už nepotřebujeme, protože ten kostruktor nejde zvenku zavolat.

2019-11-29 14:34 UTC, fmasa commented on src/Wsdl/WebServiceName.php
> +  public static function getConstants(): array
Zvážil bych jestli nepoužít popisnější název, když je to teď public API. Alespoň něco jako `getAll()`.

2019-12-28 19:31 UTC, JindrichPilar commented
Díky za review, připomínky jsem zapracoval.

2019-12-28 19:50 UTC, merged