GitHub actions
skaut/Skautis pull request #98
Opened 2021-01-08 14:38 UTC by sinacek

2021-01-08 20:07 UTC, JindrichPilar requested changes

2021-01-08 20:07 UTC, JindrichPilar commented on .gitignore
> -composer.lock
Za jakym ucelem se `composer.lock` pridava? Jestli dobre koukam, tak jelikoz actions volaji `composer update` a composer.lock slouzi maximalne jako dolni hranice zavislosti.


(`,lock` knihovny je AFAIK pri instalaci do aplikace ignorovan)

2021-01-08 20:07 UTC, JindrichPilar commented on .github/workflows/main.yml
> +  coding-standard:
`parallel-lint` validuje syntaxi php, nikoliv coding standard

2021-01-08 20:07 UTC, JindrichPilar commented on .github/workflows/main.yml
> +        php-versions: ['7.4', '8.0']
PHP 7.3 ma security support jeste 10 mesicu, test bych ponechal.

2021-01-08 20:07 UTC, JindrichPilar commented on .github/workflows/main.yml
> +        php-versions: ['7.4', '8.0']
Je potreba upravit `composer.json` aby dovolil nainstalovat pouze na testovanych verzich.

2021-01-08 20:07 UTC, JindrichPilar commented on .github/workflows/main.yml
> +        run: composer update --no-interaction -o --dev --prefer-dist
Je duvod proc tady je `-o` a u ostatnich ne?

Jsem pro `-o` dat vsude a jeste pridat `-a`.

2021-01-08 20:07 UTC, JindrichPilar commented on .github/workflows/main.yml
> +        run: composer update --no-interaction -o --dev --prefer-dist
> You are using the deprecated option "--dev". It has no effect and will break in Composer 3.

2021-01-08 20:07 UTC, JindrichPilar commented on .github/workflows/main.yml
> +    runs-on: ubuntu-latest
Bylo by dobre specifikovat konkretni verzi. Jak bude GitHub updatovat na co ukazuje latest, muze se stat ze verze PHP kterou testujeme tam uz nebude. Viz tabulka https://github.com/shivammathur/setup-php#github-hosted-runners

2021-01-08 22:07 UTC, sinacek commented on .github/workflows/main.yml
> +        php-versions: ['7.4', '8.0']
je to tak zásadní? Do tedka jsme to tam neměli

2021-01-08 22:10 UTC, sinacek commented on .gitignore
> -composer.lock
ok, odebral jsem to

2021-01-08 22:10 UTC, sinacek commented on .github/workflows/main.yml
> +  coding-standard:
prejmenovano

2021-01-08 22:11 UTC, sinacek commented on .github/workflows/main.yml
> +        php-versions: ['7.4', '8.0']
upraveno

2021-01-08 22:11 UTC, sinacek commented on .github/workflows/main.yml
> +        run: composer update --no-interaction -o --dev --prefer-dist
upraveno

2021-01-08 22:11 UTC, sinacek commented on .github/workflows/main.yml
> +        run: composer update --no-interaction -o --dev --prefer-dist
upraveno

2021-01-08 22:11 UTC, sinacek commented on .github/workflows/main.yml
> +    runs-on: ubuntu-latest
upraveno

2021-01-08 23:11 UTC, JindrichPilar commented on .github/workflows/main.yml
> +        php-versions: ['7.4', '8.0']
Ano, je. Neni dobre aby uzivatel pouzival PHP na nizsi verzi nez kterou testujeme. PHP 7.4 napr. umoznuje pouzivat typed properties, 7.2 ne.

Meli jsme to tak, slo instalovat pouze testovane a vyssi.
V composer.json je  ` "php": ">=7.2"` a v Travisu bylo

```yaml
php:	
  - 7.2	
  - 7.3	
  - 7.4	
  - nightly
```

2021-01-08 23:13 UTC, JindrichPilar commented on composer.lock
> +{
Tenhle soubor by nemel byt commitnuty.

2021-01-09 08:23 UTC, sinacek commented on composer.lock
> +{
uplne jsem odebral ty commity

2021-01-09 08:28 UTC, sinacek commented on .github/workflows/main.yml
> +        php-versions: ['7.4', '8.0']
sorry, pochopil jsem to uplně jinak původně a to mi nedávalo smysl. Tohle jsem samozrejmě upravil na `>=7.3`

2021-01-10 09:16 UTC, JindrichPilar approved these changes

2021-01-10 21:07 UTC, merged